### ISSUE TITLE
Naming scheme for block IDs could be improved

### ISSUE THREAD

**Issue by KatalystPrime** [polyvalord/extcaves#13]
The block IDs have redundant and inefficient naming schemes, such as
`stone_cobble_dirtstone`. Why have `stone` as a prefix, all but one of the blocks with the `stone` prefix have stone _in their name_ apart from marble? It seems like unnecessary complication which leads to a less preferable user experience. You could simplify the worst offender, `stone_cobble_dirtstone` to just `dirt_cobblestone`. You never see IDs like this in the base game. These look like in-development IDs that were never changed afterwards to reflect their finalised names. 
This could be excusable if this was in alpha or beta versions, but release versions have already been released.

**Comment by polyvalord** [comment]
Well I name everything this way because it's easier to separate my blocks & items from the game, easier to rename and locate files. I did not have any issues related to that either on management or debugging.
I understand this could be problematic especially if I'm working with other peoples or need a compatibility with some other mods but it's currently not the case.
I like it this way and I do not think this could impact any user experience as long as it is working well in game and not causing any crashes / lags / bugs - I think people are fine with it in general.

**Comment by polyvalord** [comment]
All ids are updated for 1.16
